### ISSUE TITLE
only the Main tab is working

### ISSUE THREAD

**Issue by hekr82** [OWASP/www-project-internet-of-things#1]
On https://owasp.org/www-project-internet-of-things/ only the Main tab is working.
Switching to other tabs like https://www.owasp.org/index.php/OWASP_Internet_of_Things_Project#tab=Firmware_Security_Testing_Methodology does not work.

Tested on both Google Chrome Version 79.0.3945.130 as well as Firefox Version 72.0.2

**Comment by scriptingxss** [comment]
Thanks for reporting, I will update. OWASP recently migrated and domains have changed. The project wiki URL is https://wiki.owasp.org/index.php/OWASP_Internet_of_Things_Project#tab=Firmware_Security_Testing_Methodology.

**Comment by scriptingxss** [comment]
Updated.
